png(filename = 'plot4.png', width = 500, height = 500, units = 'px')
library(sqldf)
data <- read.csv.sql("household_power_consumption.txt", sep=";",sql = 'select * from file where Date = "1/2/2007" union select * from file where Date = "2/2/2007" ')
BetterDate <- strptime(paste(data$Date,"-",data$Time),format="%d/%m/%Y - %H:%M:%S")
par(mfrow=c(2,2))
with(data, {
	plot(BetterDate,Global_active_power,type="l",ylab="Global Active Power",xlab="")
	plot(BetterDate,Voltage,type="l",xlab="datetime")
	plot(BetterDate,Sub_metering_1,type="l",ylab="Energy sub meterin",xlab="")
	lines(BetterDate,Sub_metering_2,col="red")
	lines(BetterDate,Sub_metering_3,col="blue")
	legend(x="topright", legend=c("Sub_metering_1", "Sub_metering_2","Sub_metering_3"), col=c("black","red","blue"), lty=1)
	plot(BetterDate,Global_reactive_power,type="l",xlab="datetime")
})
dev.off()