png(filename = 'plot2.png', width = 500, height = 500, units = 'px')
library(sqldf)
data <- read.csv.sql("household_power_consumption.txt", sep=";",sql = 'select * from file where Date = "1/2/2007" union select * from file where Date = "2/2/2007" ')
BetterDate <- strptime(paste(data$Date,"-",data$Time),format="%d/%m/%Y - %H:%M:%S")
plot(BetterDate,data$Global_active_power,type="l",ylab="Global Active Power (kilowatts)",xlab="")
dev.off()