png(filename = 'plot3.png', width = 500, height = 500, units = 'px')
library(sqldf)
data <- read.csv.sql("household_power_consumption.txt", sep=";",sql = 'select * from file where Date = "1/2/2007" union select * from file where Date = "2/2/2007" ')
BetterDate <- strptime(paste(data$Date,"-",data$Time),format="%d/%m/%Y - %H:%M:%S")
plot(BetterDate,data$Sub_metering_1,type="l",ylab="Energy sub meterin",xlab="")
lines(BetterDate,data$Sub_metering_2,col="red")
lines(BetterDate,data$Sub_metering_3,col="blue")
legend(x="topright", legend=c("Sub_metering_1", "Sub_metering_2","Sub_metering_3"), col=c("black","red","blue"), lty=1)
dev.off()